setup: Fix requirements parsing
Currently errors with python-pip-6.0.8-1.fc22.noarch

$ python setup.py test --ro-functional --rw-functional
Traceback (most recent call last):
  File "setup.py", line 181, in <module>
    str(ir.req) for ir in parse_requirements(fname)
  File "/usr/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session