Bug.__str__: encode string before returning
'print bug' calls str(), and even when the LC_* environment variables are set
to UTF-8, str() uses the 'ascii' codec to encode the unicode string, and causes
errors when "print bug" or antyhing that calls str(bug) is used. Example:

    File "/usr/bin/bugzilla", line 507, in main
      print b
  UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 41: ordinal not in range(128)

Fortunately the command-line tool was already changed to not use "print bug"
anymore, but this should make other code using "print bug" or "str(bug)" safer.

This patch makes __str__() encode the unicode string to the system locale,
making 'print bug' and str(bug) work as expected.

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>