Fix for writing tokenfile on python3 on windows
The tokenfile must be opened in text mode to avoid an error on write:

TypeError: 'str' does not support the buffer interface

https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.write

Tested with Python 3.4.1 on Windows.